-- Add blur data and batch metadata fields to gallery table
ALTER TABLE gallery
  ADD COLUMN IF NOT EXISTS blur_data TEXT,
  ADD COLUMN IF NOT EXISTS credits TEXT,
  ADD COLUMN IF NOT EXISTS catalog_id VARCHAR(255),
  ADD COLUMN IF NOT EXISTS magazine_issue VARCHAR(255);

-- Add index for catalog_id queries
CREATE INDEX IF NOT EXISTS idx_gallery_catalog_id ON gallery(catalog_id);

-- Add index for magazine_issue queries
CREATE INDEX IF NOT EXISTS idx_gallery_magazine_issue ON gallery(magazine_issue);

-- Add comment for documentation
COMMENT ON COLUMN gallery.blur_data IS 'Base64 blur placeholder for progressive image loading (generated by Plaiceholder)';
COMMENT ON COLUMN gallery.credits IS 'Source credits for images (e.g., magazine name, photographer)';
COMMENT ON COLUMN gallery.catalog_id IS 'Unique catalog identifier (e.g., LMSY-G-2025-001)';
COMMENT ON COLUMN gallery.magazine_issue IS 'Magazine issue name (e.g., Vogue Thailand January 2025)';
